spring:
  application:
    name: websocket-server

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  redis:
    host: localhost
    port: 6379
    password:
    database: 0

  datasource:
    url: jdbc:postgresql://localhost:5432/ChatApplicationDB

  jpa:
    hibernate:
      ddl-auto: validate
    show:
      sql: true
    properties:
      hibernate:
        format_sql: true


app:
  kafka:
    routing-topic: CHAT-EVENTS
    group-id: ${app.server-id}

    messages-event-topic: CHAT-MESSAGES

  server-id: default-server


#  spring.datasource.url=jdbc:postgresql://localhost:5432/inventorydb
#  spring.jpa.hibernate.ddl-auto=create
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.format_sql=true